//go:build !ignore_autogenerated

/*
Copyright 2026 Thomas Boerger <thomas@webhippie.de>.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package common

import ()

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigMapRefOrVal) DeepCopyInto(out *ConfigMapRefOrVal) {
	*out = *in
	out.ConfigMapKeySelector = in.ConfigMapKeySelector
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigMapRefOrVal.
func (in *ConfigMapRefOrVal) DeepCopy() *ConfigMapRefOrVal {
	if in == nil {
		return nil
	}
	out := new(ConfigMapRefOrVal)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretKeyRefOrVal) DeepCopyInto(out *SecretKeyRefOrVal) {
	*out = *in
	out.SecretKeySelector = in.SecretKeySelector
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretKeyRefOrVal.
func (in *SecretKeyRefOrVal) DeepCopy() *SecretKeyRefOrVal {
	if in == nil {
		return nil
	}
	out := new(SecretKeyRefOrVal)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourceRef) DeepCopyInto(out *SourceRef) {
	*out = *in
	if in.ConfigMapKeyRef != nil {
		in, out := &in.ConfigMapKeyRef, &out.ConfigMapKeyRef
		*out = new(ConfigMapKeySelector)
		**out = **in
	}
	if in.SecretKeyRef != nil {
		in, out := &in.SecretKeyRef, &out.SecretKeyRef
		*out = new(SecretKeySelector)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourceRef.
func (in *SourceRef) DeepCopy() *SourceRef {
	if in == nil {
		return nil
	}
	out := new(SourceRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourceRefOrVal) DeepCopyInto(out *SourceRefOrVal) {
	*out = *in
	if in.SourceRef != nil {
		in, out := &in.SourceRef, &out.SourceRef
		*out = new(SourceRef)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourceRefOrVal.
func (in *SourceRefOrVal) DeepCopy() *SourceRefOrVal {
	if in == nil {
		return nil
	}
	out := new(SourceRefOrVal)
	in.DeepCopyInto(out)
	return out
}
