---
apiVersion: identity.keycloak-operator.webhippie.de/v1alpha1
kind: OIDCAdvancedGroupMapper

metadata:
  name: oidcadvancedgroupmapper-sample
  labels:
    app.kubernetes.io/name: keycloak-operator
    app.kubernetes.io/managed-by: kustomize

spec:
  identityProviderRef:
    name: oidcidentityprovider-sample

  name: engineering-group-mapper
  group: /engineering
  claims:
    department: engineering

...
