---
apiVersion: identity.keycloak-operator.webhippie.de/v1alpha1
kind: HardcodedRoleMapper

metadata:
  name: hardcodedrolemapper-sample
  labels:
    app.kubernetes.io/name: keycloak-operator
    app.kubernetes.io/managed-by: kustomize

spec:
  identityProviderRef:
    name: oidcidentityprovider-sample

  name: grant-realm-admin
  role: realm-admin

...
