---
apiVersion: identity.keycloak-operator.webhippie.de/v1alpha1
kind: AttributeImporterMapper

metadata:
  name: attributeimportermapper-sample
  labels:
    app.kubernetes.io/name: keycloak-operator
    app.kubernetes.io/managed-by: kustomize

spec:
  identityProviderRef:
    name: oidcidentityprovider-sample

  name: import-preferred-username
  userAttribute: username
  claimName: preferred_username

...
