---
apiVersion: openid.keycloak-operator.webhippie.de/v1alpha1
kind: DefaultScopes

metadata:
  name: defaultscopes-sample
  labels:
    app.kubernetes.io/name: keycloak-operator
    app.kubernetes.io/managed-by: kustomize

spec:
  clientRef:
    name: openidclient-sample

  defaultScopes:
    - profile
    - email
    - roles

...
