---
apiVersion: openid.keycloak-operator.webhippie.de/v1alpha1
kind: UserAttributeProtocolMapper

metadata:
  name: userattributeprotocolmapper-sample
  labels:
    app.kubernetes.io/name: keycloak-operator
    app.kubernetes.io/managed-by: kustomize

spec:
  clientRef:
    name: openidclient-sample

  name: department
  userAttribute: department
  claimName: department
  claimValueType: String
  multivalued: false
  aggregateAttributes: true
  addToIDToken: true
  addToAccessToken: true
  addToUserInfo: true
  addToTokenIntrospection: true

...
