---
apiVersion: openid.keycloak-operator.webhippie.de/v1alpha1
kind: FullNameProtocolMapper

metadata:
  name: fullnameprotocolmapper-sample
  labels:
    app.kubernetes.io/name: keycloak-operator
    app.kubernetes.io/managed-by: kustomize

spec:
  clientRef:
    name: openidclient-sample

  name: full-name
  addToIDToken: true
  addToAccessToken: true
  addToUserInfo: true

...
