---
apiVersion: openid.keycloak-operator.webhippie.de/v1alpha1
kind: OpenIDClient

metadata:
  name: openidclient-sample
  labels:
    app.kubernetes.io/name: keycloak-operator
    app.kubernetes.io/managed-by: kustomize

spec:
  realmRef:
    name: realm-sample

  clientID: sample-client
  name: Sample Client
  description: A sample OpenID client managed by keycloak-operator.
  accessType: CONFIDENTIAL
  clientSecret:
    value: change-me
  standardFlowEnabled: true
  directAccessGrantsEnabled: true
  validRedirectURIs:
    - "https://example.com/*"
  webOrigins:
    - "https://example.com"

...
