---
apiVersion: keycloak-operator.webhippie.de/v1alpha1
kind: Keycloak

metadata:
  name: keycloak-sample
  namespace: keycloak-operator-system
  labels:
    app.kubernetes.io/name: keycloak-operator
    app.kubernetes.io/managed-by: kustomize

spec:
  url: https://keycloak.example.com
  username:
    secretKeyRef:
      name: keycloak-admin
      key: username
  password:
    secretKeyRef:
      name: keycloak-admin
      key: password

...
