---
apiVersion: keycloak-operator.webhippie.de/v1alpha1
kind: User

metadata:
  name: user-sample
  namespace: keycloak-operator-system
  labels:
    app.kubernetes.io/name: keycloak-operator
    app.kubernetes.io/managed-by: kustomize

spec:
  realmRef:
    name: realm-sample

  username: sample-user

  password:
    value: change-me
  temporary: true

  groups:
    - group-sample

  realmRoles:
    - realm-role-sample

...
