//go:build !ignore_autogenerated

/*
Copyright 2026 Thomas Boerger <thomas@webhippie.de>.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/kubehippie/keycloak-operator/api/common"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AttributeImporterMapper) DeepCopyInto(out *AttributeImporterMapper) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AttributeImporterMapper.
func (in *AttributeImporterMapper) DeepCopy() *AttributeImporterMapper {
	if in == nil {
		return nil
	}
	out := new(AttributeImporterMapper)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AttributeImporterMapper) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AttributeImporterMapperList) DeepCopyInto(out *AttributeImporterMapperList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AttributeImporterMapper, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AttributeImporterMapperList.
func (in *AttributeImporterMapperList) DeepCopy() *AttributeImporterMapperList {
	if in == nil {
		return nil
	}
	out := new(AttributeImporterMapperList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AttributeImporterMapperList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AttributeImporterMapperSpec) DeepCopyInto(out *AttributeImporterMapperSpec) {
	*out = *in
	if in.IdentityProviderRef != nil {
		in, out := &in.IdentityProviderRef, &out.IdentityProviderRef
		*out = new(common.IdentityProviderRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AttributeImporterMapperSpec.
func (in *AttributeImporterMapperSpec) DeepCopy() *AttributeImporterMapperSpec {
	if in == nil {
		return nil
	}
	out := new(AttributeImporterMapperSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AttributeImporterMapperStatus) DeepCopyInto(out *AttributeImporterMapperStatus) {
	*out = *in
	if in.KeycloakID != nil {
		in, out := &in.KeycloakID, &out.KeycloakID
		*out = new(string)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AttributeImporterMapperStatus.
func (in *AttributeImporterMapperStatus) DeepCopy() *AttributeImporterMapperStatus {
	if in == nil {
		return nil
	}
	out := new(AttributeImporterMapperStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomProviderMapper) DeepCopyInto(out *CustomProviderMapper) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomProviderMapper.
func (in *CustomProviderMapper) DeepCopy() *CustomProviderMapper {
	if in == nil {
		return nil
	}
	out := new(CustomProviderMapper)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CustomProviderMapper) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomProviderMapperList) DeepCopyInto(out *CustomProviderMapperList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CustomProviderMapper, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomProviderMapperList.
func (in *CustomProviderMapperList) DeepCopy() *CustomProviderMapperList {
	if in == nil {
		return nil
	}
	out := new(CustomProviderMapperList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CustomProviderMapperList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomProviderMapperSpec) DeepCopyInto(out *CustomProviderMapperSpec) {
	*out = *in
	if in.IdentityProviderRef != nil {
		in, out := &in.IdentityProviderRef, &out.IdentityProviderRef
		*out = new(common.IdentityProviderRef)
		**out = **in
	}
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomProviderMapperSpec.
func (in *CustomProviderMapperSpec) DeepCopy() *CustomProviderMapperSpec {
	if in == nil {
		return nil
	}
	out := new(CustomProviderMapperSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomProviderMapperStatus) DeepCopyInto(out *CustomProviderMapperStatus) {
	*out = *in
	if in.KeycloakID != nil {
		in, out := &in.KeycloakID, &out.KeycloakID
		*out = new(string)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomProviderMapperStatus.
func (in *CustomProviderMapperStatus) DeepCopy() *CustomProviderMapperStatus {
	if in == nil {
		return nil
	}
	out := new(CustomProviderMapperStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HardcodedRoleMapper) DeepCopyInto(out *HardcodedRoleMapper) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HardcodedRoleMapper.
func (in *HardcodedRoleMapper) DeepCopy() *HardcodedRoleMapper {
	if in == nil {
		return nil
	}
	out := new(HardcodedRoleMapper)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HardcodedRoleMapper) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HardcodedRoleMapperList) DeepCopyInto(out *HardcodedRoleMapperList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HardcodedRoleMapper, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HardcodedRoleMapperList.
func (in *HardcodedRoleMapperList) DeepCopy() *HardcodedRoleMapperList {
	if in == nil {
		return nil
	}
	out := new(HardcodedRoleMapperList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *HardcodedRoleMapperList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HardcodedRoleMapperSpec) DeepCopyInto(out *HardcodedRoleMapperSpec) {
	*out = *in
	if in.IdentityProviderRef != nil {
		in, out := &in.IdentityProviderRef, &out.IdentityProviderRef
		*out = new(common.IdentityProviderRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HardcodedRoleMapperSpec.
func (in *HardcodedRoleMapperSpec) DeepCopy() *HardcodedRoleMapperSpec {
	if in == nil {
		return nil
	}
	out := new(HardcodedRoleMapperSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HardcodedRoleMapperStatus) DeepCopyInto(out *HardcodedRoleMapperStatus) {
	*out = *in
	if in.KeycloakID != nil {
		in, out := &in.KeycloakID, &out.KeycloakID
		*out = new(string)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HardcodedRoleMapperStatus.
func (in *HardcodedRoleMapperStatus) DeepCopy() *HardcodedRoleMapperStatus {
	if in == nil {
		return nil
	}
	out := new(HardcodedRoleMapperStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OIDCAdvancedGroupMapper) DeepCopyInto(out *OIDCAdvancedGroupMapper) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OIDCAdvancedGroupMapper.
func (in *OIDCAdvancedGroupMapper) DeepCopy() *OIDCAdvancedGroupMapper {
	if in == nil {
		return nil
	}
	out := new(OIDCAdvancedGroupMapper)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OIDCAdvancedGroupMapper) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OIDCAdvancedGroupMapperList) DeepCopyInto(out *OIDCAdvancedGroupMapperList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OIDCAdvancedGroupMapper, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OIDCAdvancedGroupMapperList.
func (in *OIDCAdvancedGroupMapperList) DeepCopy() *OIDCAdvancedGroupMapperList {
	if in == nil {
		return nil
	}
	out := new(OIDCAdvancedGroupMapperList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OIDCAdvancedGroupMapperList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OIDCAdvancedGroupMapperSpec) DeepCopyInto(out *OIDCAdvancedGroupMapperSpec) {
	*out = *in
	if in.IdentityProviderRef != nil {
		in, out := &in.IdentityProviderRef, &out.IdentityProviderRef
		*out = new(common.IdentityProviderRef)
		**out = **in
	}
	if in.Claims != nil {
		in, out := &in.Claims, &out.Claims
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.ClaimValuesRegex != nil {
		in, out := &in.ClaimValuesRegex, &out.ClaimValuesRegex
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OIDCAdvancedGroupMapperSpec.
func (in *OIDCAdvancedGroupMapperSpec) DeepCopy() *OIDCAdvancedGroupMapperSpec {
	if in == nil {
		return nil
	}
	out := new(OIDCAdvancedGroupMapperSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OIDCAdvancedGroupMapperStatus) DeepCopyInto(out *OIDCAdvancedGroupMapperStatus) {
	*out = *in
	if in.KeycloakID != nil {
		in, out := &in.KeycloakID, &out.KeycloakID
		*out = new(string)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OIDCAdvancedGroupMapperStatus.
func (in *OIDCAdvancedGroupMapperStatus) DeepCopy() *OIDCAdvancedGroupMapperStatus {
	if in == nil {
		return nil
	}
	out := new(OIDCAdvancedGroupMapperStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OIDCIdentityProvider) DeepCopyInto(out *OIDCIdentityProvider) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OIDCIdentityProvider.
func (in *OIDCIdentityProvider) DeepCopy() *OIDCIdentityProvider {
	if in == nil {
		return nil
	}
	out := new(OIDCIdentityProvider)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OIDCIdentityProvider) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OIDCIdentityProviderList) DeepCopyInto(out *OIDCIdentityProviderList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OIDCIdentityProvider, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OIDCIdentityProviderList.
func (in *OIDCIdentityProviderList) DeepCopy() *OIDCIdentityProviderList {
	if in == nil {
		return nil
	}
	out := new(OIDCIdentityProviderList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OIDCIdentityProviderList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OIDCIdentityProviderSpec) DeepCopyInto(out *OIDCIdentityProviderSpec) {
	*out = *in
	if in.RealmRef != nil {
		in, out := &in.RealmRef, &out.RealmRef
		*out = new(common.RealmRef)
		**out = **in
	}
	if in.DisplayName != nil {
		in, out := &in.DisplayName, &out.DisplayName
		*out = new(string)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.ClientSecret != nil {
		in, out := &in.ClientSecret, &out.ClientSecret
		*out = new(common.SecretKeyRefOrVal)
		(*in).DeepCopyInto(*out)
	}
	if in.UserInfoURL != nil {
		in, out := &in.UserInfoURL, &out.UserInfoURL
		*out = new(string)
		**out = **in
	}
	if in.JwksURL != nil {
		in, out := &in.JwksURL, &out.JwksURL
		*out = new(string)
		**out = **in
	}
	if in.LogoutURL != nil {
		in, out := &in.LogoutURL, &out.LogoutURL
		*out = new(string)
		**out = **in
	}
	if in.Issuer != nil {
		in, out := &in.Issuer, &out.Issuer
		*out = new(string)
		**out = **in
	}
	if in.DefaultScopes != nil {
		in, out := &in.DefaultScopes, &out.DefaultScopes
		*out = new(string)
		**out = **in
	}
	if in.ValidateSignature != nil {
		in, out := &in.ValidateSignature, &out.ValidateSignature
		*out = new(bool)
		**out = **in
	}
	if in.BackchannelSupported != nil {
		in, out := &in.BackchannelSupported, &out.BackchannelSupported
		*out = new(bool)
		**out = **in
	}
	if in.HideOnLoginPage != nil {
		in, out := &in.HideOnLoginPage, &out.HideOnLoginPage
		*out = new(bool)
		**out = **in
	}
	if in.StoreToken != nil {
		in, out := &in.StoreToken, &out.StoreToken
		*out = new(bool)
		**out = **in
	}
	if in.TrustEmail != nil {
		in, out := &in.TrustEmail, &out.TrustEmail
		*out = new(bool)
		**out = **in
	}
	if in.LinkOnly != nil {
		in, out := &in.LinkOnly, &out.LinkOnly
		*out = new(bool)
		**out = **in
	}
	if in.FirstBrokerLoginFlowAlias != nil {
		in, out := &in.FirstBrokerLoginFlowAlias, &out.FirstBrokerLoginFlowAlias
		*out = new(string)
		**out = **in
	}
	if in.PostBrokerLoginFlowAlias != nil {
		in, out := &in.PostBrokerLoginFlowAlias, &out.PostBrokerLoginFlowAlias
		*out = new(string)
		**out = **in
	}
	if in.SyncMode != nil {
		in, out := &in.SyncMode, &out.SyncMode
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OIDCIdentityProviderSpec.
func (in *OIDCIdentityProviderSpec) DeepCopy() *OIDCIdentityProviderSpec {
	if in == nil {
		return nil
	}
	out := new(OIDCIdentityProviderSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OIDCIdentityProviderStatus) DeepCopyInto(out *OIDCIdentityProviderStatus) {
	*out = *in
	if in.KeycloakID != nil {
		in, out := &in.KeycloakID, &out.KeycloakID
		*out = new(string)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OIDCIdentityProviderStatus.
func (in *OIDCIdentityProviderStatus) DeepCopy() *OIDCIdentityProviderStatus {
	if in == nil {
		return nil
	}
	out := new(OIDCIdentityProviderStatus)
	in.DeepCopyInto(out)
	return out
}
