{{- if .Values.rbac.enable }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "chart.fullname" . }}-manager
  labels:
    {{- include "chart.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - secrets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - identity.keycloak-operator.webhippie.de
    resources:
      - attributeimportermappers
      - customprovidermappers
      - hardcodedrolemappers
      - oidcadvancedgroupmappers
      - oidcidentityproviders
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - identity.keycloak-operator.webhippie.de
    resources:
      - attributeimportermappers/finalizers
      - customprovidermappers/finalizers
      - hardcodedrolemappers/finalizers
      - oidcadvancedgroupmappers/finalizers
      - oidcidentityproviders/finalizers
    verbs:
      - update
  - apiGroups:
      - identity.keycloak-operator.webhippie.de
    resources:
      - attributeimportermappers/status
      - customprovidermappers/status
      - hardcodedrolemappers/status
      - oidcadvancedgroupmappers/status
      - oidcidentityproviders/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - keycloak-operator.webhippie.de
    resources:
      - groups
      - keycloaks
      - realms
      - roles
      - users
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - keycloak-operator.webhippie.de
    resources:
      - groups/finalizers
      - keycloaks/finalizers
      - realms/finalizers
      - roles/finalizers
      - users/finalizers
    verbs:
      - update
  - apiGroups:
      - keycloak-operator.webhippie.de
    resources:
      - groups/status
      - keycloaks/status
      - realms/status
      - roles/status
      - users/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - openid.keycloak-operator.webhippie.de
    resources:
      - audienceprotocolmappers
      - clientscopes
      - defaultscopes
      - fullnameprotocolmappers
      - groupmembershipprotocolmappers
      - openidclients
      - userattributeprotocolmappers
      - userpropertyprotocolmappers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - openid.keycloak-operator.webhippie.de
    resources:
      - audienceprotocolmappers/finalizers
      - clientscopes/finalizers
      - defaultscopes/finalizers
      - fullnameprotocolmappers/finalizers
      - groupmembershipprotocolmappers/finalizers
      - openidclients/finalizers
      - userattributeprotocolmappers/finalizers
      - userpropertyprotocolmappers/finalizers
    verbs:
      - update
  - apiGroups:
      - openid.keycloak-operator.webhippie.de
    resources:
      - audienceprotocolmappers/status
      - clientscopes/status
      - defaultscopes/status
      - fullnameprotocolmappers/status
      - groupmembershipprotocolmappers/status
      - openidclients/status
      - userattributeprotocolmappers/status
      - userpropertyprotocolmappers/status
    verbs:
      - get
      - patch
      - update
  {{- if .Values.rbac.extraRules }}
  {{- toYaml .Values.rbac.extraRules | nindent 2 }}
  {{- end }}
{{- end -}}
